---

- name: "[1 - 4] slurm template config to destination"
  template: src={{ item }}.j2 dest=/etc/sysconfig/slurm/{{ item }}
  with_items:
    - slurmdbd.conf
    - slurm.conf

- name: "[2 - 4] Start service slurmdbd, if not running"
  service: name=slurmdbd state=restarted

- name: "[3 - 4] Start service slurmctld, if not running"
  service: name=slurmctld state=restarted

- name: "[2 - 4] Add cluster to sacctmgr"
  shell: "sacctmgr -i add cluster cluster"
