---
# https://munge.googlecode.com/files/munge-0.5.11.tar.bz2

- name: Install munge
  yum: name={{ item }} state=present
  with_items:
    - munge
    - munge-devel

- name: create-munge-key on /etc/munge/munge.key
  shell: create-munge-key
#  shell: dd if=/dev/urandom bs=1 count=1024 >/etc/munge/munge.key

- name: Change premisions
  file: path=/etc/munge/ owner=munge group=munge recurse=yes state=directory mode=0700
  file: path=/var/lib/munge/ owner=munge group=munge recurse=yes state=directory mode=0711
  file: path=/var/log/munge/ owner=munge group=munge recurse=yes state=directory mode=0700
  file: path=/var/run/munge/ owner=munge group=munge recurse=yes state=directory mode=0755


- name: Start service munge, if not running
  service: name=munge state=restarted


- name: Teste
  shell: munge -n | unmunge
