---

# - name: Copy script to HC
#   copy: src=configgenerate/{{ item }} dest=~/downloads/configgenerate/{{ item }} owner=root group=root mode=0744
#   with_items:
#    - conf
#    - generate.pl
#    - slurm.template

- name: slurm template config to destination
  template: src=slurm.conf.j2 dest=/etc/sysconfig/slurm/slurm.conf

# - name: Create a config file on /usr/local/etc/slurm.conf
#   shell: cd ~/downloads/configgenerate/ && ./generate.pl slurm.template /etc/sysconfig/slurm/slurm.conf

- name: Restarted service slurmd
  service: name=slurmd state=restarted
