---
- shell: "rpm -Uvh http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm"

- name: Install mysql-community-server
  yum: name={{ item }} state=present
  with_items:
   - mysql-community-server
   - mysql-community-devel

- name: Start service munge, if not running
  service: name=mysql state=restarted

- name: Create database and tables
  shell: mysql -u root -e "create database slurm_acct_db;"
  shell: mysql -u root -e "CREATE USER 'slurm'@'localhost';"
  shell: mysql -u root -e "grant usage on *.* to 'slurm'@'localhost';"
  shell: mysql -u root -e "set password for 'slurm'@'localhost' = password('isec')"
  shell: mysql -u root -e "grant all privileges on slurm_acct_db.* to 'slurm'@'localhost';"
  shell: mysql -u root -e "flush privileges;"
