---
- name: "Install project dependencies"
  yum: "name={{ item }} state=latest"
  with_items:
    - epel-release
    - rpm-build
    - redhat-rpm-config
    - asciidoc
    - hmaccalc
    - perl-ExtUtils-Embed
    - xmlto
    - audit-libs-devel
    - binutils-devel
    - elfutils-devel
    - elfutils-libelf-devel
    - newt-devel
    - python-devel
    - zlib-devel
    - openssl-devel
    - gcc
    - kernel-devel
    - git

- name: Create dirs
  shell: mkdir ~/downloads/ && mkdir /var/log/slurm/  &&  mkdir /etc/slurm
