---
# More information of BLCR on: http://crd.lbl.gov/departments/computer-science/CLaSS/research/BLCR/#toc-anchor-4

 - name: download file from BLCR repo
   get_url: url=https://upc-bugs.lbl.gov/blcr-dist/blcr-0.8.6_b4.tar.gz dest=~/downloads/

 - name: unTar
   shell: cd ~/downloads/ && tar -xvf ~/downloads/blcr-0.8.6_b4.tar.gz

 - name: Configure instalation
   shell: "cd ~/downloads/blcr-0.8.6_b4 && ./configure "

 - name: Make
   shell: "cd ~/downloads/blcr-0.8.6_b4 && make"

 - name: Make Install
   shell: "cd ~/downloads/blcr-0.8.6_b4 && make install"
