---
# More information of BLCR on: http://crd.lbl.gov/departments/computer-science/CLaSS/research/BLCR/#toc-anchor-4

 - name: "[1 - 5] download file from BLCR repo"
   get_url: url=https://upc-bugs.lbl.gov/blcr-dist/blcr-0.8.6_b4.tar.gz dest=~/downloads/

 - name: "[2 - 5] unTar"
   shell: cd ~/downloads/ && tar -xvf ~/downloads/blcr-0.8.6_b4.tar.gz

 - name: "[3 - 5] Configure instalation"
   shell: "cd ~/downloads/blcr-0.8.6_b4 && ./configure CC='gcc -m64' --with-linux=/usr/src/kernels/3.10.0-229.11.1.el7.x86_64/"

 - name: "[4 - 5] Make"
   shell: "cd ~/downloads/blcr-0.8.6_b4 && make"

 - name: "[5 - 5] Make Install"
   shell: "cd ~/downloads/blcr-0.8.6_b4 && make install"
